### ISSUE TITLE
TSK-4.4 Java Bindings not working on Linux (problem persists)

### ISSUE THREAD

**Issue by mauriciolage** [sleuthkit/sleuthkit#1024]
I'm facing **exactly** the same problem reported by lfcnassif on issue #799.

> Caused by: java.lang.UnsatisfiedLinkError: /tmp/indexador-temp1511961961689/indexador-temp1511961961980/libtsk_jni.so: /tmp/indexador-temp1511961961689/indexador-temp1511961961980/libtsk_jni.so: undefined symbol: _ZTV19TskIsImageSupported
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_131]
	at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_131]
	at java.lang.System.load(System.java:1086) ~[?:1.8.0_131]
	at org.sleuthkit.datamodel.LibraryUtils.loadNativeLibFromTskJar(LibraryUtils.java:207) ~[tsk-datamodel-4.4.2-p02.jar:?]
	at org.sleuthkit.datamodel.LibraryUtils.loadSleuthkitJNI(LibraryUtils.java:73) ~[tsk-datamodel-4.4.2-p02.jar:?]
	at org.sleuthkit.datamodel.SleuthkitJNI.<clinit>(SleuthkitJNI.java:52) ~[tsk-datamodel-4.4.2-p02.jar:?]
	at org.sleuthkit.datamodel.SleuthkitCase.newCase(SleuthkitCase.java:1195) ~[tsk-datamodel-4.4.2-p02.jar:?]
	at dpf.sp.gpinf.indexer.datasource.SleuthkitReader.read(SleuthkitReader.java:269) ~[iped.jar:?]
	at dpf.sp.gpinf.indexer.datasource.ItemProducer.run(ItemProducer.java:104) ~[iped.jar:?]

I tested on TSK-4.4.2 and TSK-4.5. The fix described in [https://github.com/sleuthkit/sleuthkit/commit/aa138d8adc6ab0849d84e4a1f0c412f029a92d98](url) didn't work in my environment. 

Any troubleshooting suggestions? Thanks.

**Comment by lfcnassif** [comment]
Brian's fix on #799 worked for me (Ubuntu 14.04), but I've received reports from other colleagues that it did not work on their environments like yours. Did you try the ugly workaround of commenting out the function?
