### ISSUE TITLE
Out of Bounds Memory Access at hfs_cat_traverse

### ISSUE THREAD

**Issue by Google-Autofuzz** [sleuthkit/sleuthkit#1143]
Hello sleuthkit team,

As part of our fuzzing efforts at Google, we have identified an issue affecting
sleuthkit (tested with revision * develop 76b7b2c1a46069ae40a09dedce5bc1e375d0dc9c).

To reproduce, we are attaching a Dockerfile which compiles the project with
LLVM, taking advantage of the sanitizers that it offers. More information about
how to use the attached Dockerfile can be found here:
https://docs.docker.com/engine/reference/builder/

TL;DR instructions:
* `mkdir project`
* `cp Dockerfile.sleuthkit /path/to/project/Dockerfile`
* `docker build --no-cache /path/to/project`
* `docker run --cap-add=SYS_PTRACE -it image_id_from_docker_build`

From another terminal, outside the container:
`docker cp /path/to/attached/reproducer running_container_hostname:/fuzzing/reproducer`
(reference: https://docs.docker.com/engine/reference/commandline/cp/)

And, back inside the container:
`/fuzzing/repro.sh /fuzzing/reproducer`

Alternatively, and depending on the bug, you could use gcc, valgrind or other
instrumentation tools to aid in the investigation. The sanitizer error that we
encountered is here:

```
Error reading image file (ext2fs_open: superblock)
Invalid magic value (Not a FATFS file system (magic))
=================================================================
==20==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c0000003bc at pc 0x00000052d311 bp 0x7fff4e628840 sp 0x7fff4e628838
READ of size 1 at 0x60c0000003bc thread T0
    #0 0x52d310 in hfs_cat_traverse /fuzzing/sleuthkit/tsk/fs/hfs.c:1009:33
    #1 0x530da2 in hfs_cat_get_record_offset /fuzzing/sleuthkit/tsk/fs/hfs.c:1181:9
    #2 0x52fbc6 in hfs_cat_file_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:1603:11
    #3 0x531ef2 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2592:9
    #4 0x5241cc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #5 0x53437f in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6558:12
    #6 0x52a6a3 in tsk_fs_open_img /fuzzing/sleuthkit/tsk/fs/fs_open.c:170:16
    #7 0x51771b in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #8 0x7f465097d2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #9 0x41e039 in _start (/fuzzing/sleuthkit/tools/fstools/fls+0x41e039)

0x60c0000003bc is located 1 bytes to the right of 123-byte region [0x60c000000340,0x60c0000003bb)
allocated by thread T0 here:
    #0 0x4dc1b8 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4dc1b8)
    #1 0x5d247d in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x52bdc9 in hfs_cat_traverse /fuzzing/sleuthkit/tsk/fs/hfs.c:849:26
    #3 0x530da2 in hfs_cat_get_record_offset /fuzzing/sleuthkit/tsk/fs/hfs.c:1181:9
    #4 0x52fbc6 in hfs_cat_file_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:1603:11
    #5 0x531ef2 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2592:9
    #6 0x5241cc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #7 0x53437f in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6558:12
    #8 0x52a6a3 in tsk_fs_open_img /fuzzing/sleuthkit/tsk/fs/fs_open.c:170:16
    #9 0x51771b in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #10 0x7f465097d2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /fuzzing/sleuthkit/tsk/fs/hfs.c:1009:33 in hfs_cat_traverse
Shadow bytes around the buggy address:
  0x0c187fff8020: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c187fff8030: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c187fff8040: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c187fff8050: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c187fff8060: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
=>0x0c187fff8070: 00 00 00 00 00 00 00[03]fa fa fa fa fa fa fa fa
  0x0c187fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c187fff8090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c187fff80a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c187fff80b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c187fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==20==ABORTING
Invalid magic value (Invalid FS type in iso9660_open)
Invalid magic value (Not a NTFS file system (magic))
Invalid magic value (File is not a DOS partition (invalid primary magic) (Sector: 0))
Read offset too large for image file (tsk_img_read - 4096) (MAC Partition entry 1)
Invalid API argument (tsk_img_read: a_off: 18446744073709543424) (GPT Header structure in Sector: 18446744073709551615)
Invalid magic value (SUN (intel) partition table (Sector: 0) 3138)

```

We will gladly work with you so you can successfully confirm and reproduce this
issue. Do let us know if you have any feedback surrounding the documentation.

Once you have reproduced the issue, we'd appreciate to learn your expected
timeline for an update to be released. With any fix, please attribute the report
to "Google Autofuzz project".

We are also pleased to inform you that your project is eligible for inclusion to
the OSS-Fuzz project, which can provide additional continuous fuzzing, and
encourage you to investigate integration options.

Don't hesitate to let us know if you have any questions!

Google AutoFuzz Team

[73577591.txt](https://github.com/sleuthkit/sleuthkit/files/1753501/73577591.txt)
[artifacts_73577591.zip](https://github.com/sleuthkit/sleuthkit/files/1753502/artifacts_73577591.zip)

**Comment by esaunders** [comment]
Thanks for the patch.
