### ISSUE TITLE
Heap Out-Of-Bounds Memory Access on fls and fsstat on raw_read()

### ISSUE THREAD

**Issue by PracaGrande** [sleuthkit/sleuthkit#1221]
Hello sleuthkit team,

While fuzzing the 64-bit version of TSK with AFL compiled with ASAN, I came a cross a HEAP out-of-bounds read on a malformed raw FAT file system file. Based on the project opened issues I believe is OK to report these type of faults publicly. Please let me know if not.

This fault affects fls and fsstat with a READ of size 8 and a READ of size 8, respectively. I believe this one wasn't reported before by Google-Autofuzz but could be wrong. Details below:

```
$ fls -V
The Sleuth Kit ver 4.6.0

$ fsstat -V
The Sleuth Kit ver 4.6.0

$ uname -srvnmapi
Linux Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Running the crash file with fls compiled with ASAN:

```
$ ASAN_OPTIONS=symbolize=1 ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-3.5 fls -rpl -o 63  id:000049,sig:06,src:001
448,op:havoc,rep:64

=================================================================
==9148==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000ed78 at pc 0x0000004c6c38 bp 0x7fffffffd8f0 sp 0x7fffffffd8e8
READ of size 8 at 0x60200000ed78 thread T0
    #0 0x4c6c37 in raw_read /home/ubuntu/sleuthkit-4.6.0/tsk/img/raw.c:284:25
    #1 0x5b4479 in tsk_img_read /home/ubuntu/sleuthkit-4.6.0/tsk/img/img_io.c:100:22
    #2 0x64bb79 in tsk_fs_read /home/ubuntu/sleuthkit-4.6.0/tsk/fs/fs_io.c:116:16
    #3 0x5489ba in ntfs_dinode_lookup /home/ubuntu/sleuthkit-4.6.0/tsk/fs/ntfs.c:327:13
    #4 0x554d57 in ntfs_inode_lookup /home/ubuntu/sleuthkit-4.6.0/tsk/fs/ntfs.c:2806:9
    #5 0x4d750b in tsk_fs_file_open_meta /home/ubuntu/sleuthkit-4.6.0/tsk/fs/fs_file.c:128:9
    #6 0x54d550 in ntfs_open /home/ubuntu/sleuthkit-4.6.0/tsk/fs/ntfs.c:5126:13
    #7 0x4e0ae6 in tsk_fs_open_img /home/ubuntu/sleuthkit-4.6.0/tsk/fs/fs_open.c:124:28
    #8 0x4bf3c4 in main /home/ubuntu/sleuthkit-4.6.0/tools/fstools/fls.cpp:267:19
    #9 0x7ffff5c3182f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #10 0x4be7d8 in _start (/usr/local/bin/fls+0x4be7d8)

0x60200000ed78 is located 0 bytes to the right of 8-byte region [0x60200000ed70,0x60200000ed78)
allocated by thread T0 here:
    #0 0x4a116b in __interceptor_malloc (/usr/local/bin/fls+0x4a116b)
    #1 0x5a4e41 in tsk_malloc /home/ubuntu/sleuthkit-4.6.0/tsk/base/mymalloc.c:32:16
    #2 0x4c555f in raw_open /home/ubuntu/sleuthkit-4.6.0/tsk/img/raw.c:700:23
    #3 0x4c382f in tsk_img_open /home/ubuntu/sleuthkit-4.6.0/tsk/img/img_open.c:222:25
    #4 0x4bf2d1 in main /home/ubuntu/sleuthkit-4.6.0/tools/fstools/fls.cpp:256:17

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/ubuntu/sleuthkit-4.6.0/tsk/img/raw.c:284 raw_read
Shadow bytes around the buggy address:
  0x0c047fff9d50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fff9da0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa 00[fa]
  0x0c047fff9db0: fa fa 04 fa fa fa 00 fa fa fa fd fa fa fa fd fa
  0x0c047fff9dc0: fa fa 00 fa fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x0c047fff9dd0: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x0c047fff9de0: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x0c047fff9df0: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  ASan internal:           fe
==9148==ABORTING
```

Running the crash file with fsstat compiled with ASAN

```
ubuntu@ip-172-30-0-24:/mnt/ramdisk/FAT-corpus/syncdir-TSK/fuzzer2/crashes$ ASAN_OPTIONS=symbolize=1 ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-3.5 fsstat -o 63 id:000049,sig:06,src:001448,op:havoc,rep:64

=================================================================
==4818==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000ed78 at pc 0x0000004c6528 bp 0x7fffffffd940 sp 0x7fffffffd938
READ of size 8 at 0x60200000ed78 thread T0
    #0 0x4c6527 in raw_read /home/ubuntu/sleuthkit-4.6.0/tsk/img/raw.c:284:25
    #1 0x594b09 in tsk_img_read /home/ubuntu/sleuthkit-4.6.0/tsk/img/img_io.c:100:22
    #2 0x63cae9 in tsk_fs_read /home/ubuntu/sleuthkit-4.6.0/tsk/fs/fs_io.c:116:16
    #3 0x52ffaa in ntfs_dinode_lookup /home/ubuntu/sleuthkit-4.6.0/tsk/fs/ntfs.c:327:13
    #4 0x53c347 in ntfs_inode_lookup /home/ubuntu/sleuthkit-4.6.0/tsk/fs/ntfs.c:2806:9
    #5 0x638c9b in tsk_fs_file_open_meta /home/ubuntu/sleuthkit-4.6.0/tsk/fs/fs_file.c:128:9
    #6 0x534b40 in ntfs_open /home/ubuntu/sleuthkit-4.6.0/tsk/fs/ntfs.c:5126:13
    #7 0x4c8c86 in tsk_fs_open_img /home/ubuntu/sleuthkit-4.6.0/tsk/fs/fs_open.c:124:28
    #8 0x4bed94 in main /home/ubuntu/sleuthkit-4.6.0/tools/fstools/fsstat.cpp:156:15
    #9 0x7ffff5c3182f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #10 0x4be6b8 in _start (/usr/local/bin/fsstat+0x4be6b8)

0x60200000ed78 is located 0 bytes to the right of 8-byte region [0x60200000ed70,0x60200000ed78)
allocated by thread T0 here:
    #0 0x4a104b in __interceptor_malloc (/usr/local/bin/fsstat+0x4a104b)
    #1 0x589a61 in tsk_malloc /home/ubuntu/sleuthkit-4.6.0/tsk/base/mymalloc.c:32:16
    #2 0x4c4e4f in raw_open /home/ubuntu/sleuthkit-4.6.0/tsk/img/raw.c:700:23
    #3 0x4c311f in tsk_img_open /home/ubuntu/sleuthkit-4.6.0/tsk/img/img_open.c:222:25
    #4 0x4bec91 in main /home/ubuntu/sleuthkit-4.6.0/tools/fstools/fsstat.cpp:144:13

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/ubuntu/sleuthkit-4.6.0/tsk/img/raw.c:284 raw_read
Shadow bytes around the buggy address:
  0x0c047fff9d50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fff9da0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa 00[fa]
  0x0c047fff9db0: fa fa 04 fa fa fa 00 fa fa fa fd fa fa fa fd fa
  0x0c047fff9dc0: fa fa 00 fa fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x0c047fff9dd0: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x0c047fff9de0: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa 00 04
  0x0c047fff9df0: fa fa 00 04 fa fa 00 04 fa fa 00 04 fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  ASan internal:           fe
==4818==ABORTING
```

Without ASAN the fault is not noticeable:
```
$ fls -o 63 crash.bin
r/r * 23:
r/r * 78:
v/v 947:        $MBR
v/v 948:        $FAT1
v/v 949:        $FAT2
d/d 950:        $OrphanFiles
```
I didn't investigated the root cause, also didn't investigated if there is a way to control the READ value by manipulating the input file in some way. Attached the crash file.
[crash.zip](https://github.com/sleuthkit/sleuthkit/files/1928311/crash.zip)

Please let me know if you need any additional information.

**Comment by esaunders** [comment]
I was able to reproduce this with the sleuthkit-4.6.0 code base but it no longer appears to be an issue on develop.
I believe the following change (and possibly earlier changes) to raw.c fixed the issue:

https://github.com/sleuthkit/sleuthkit/commit/48099313099416609002e4851e3b0feb24422358#diff-c8ca8f991256671ea7deeafeb4a9bcd3

Feel free to reopen the issue if it can be reproduced.
