### ISSUE TITLE
Non Deleted NTFS files being lost with TSK-4.11.1 java AddImageProcess.run()

### ISSUE THREAD

**Issue by lfcnassif** [sleuthkit/sleuthkit#2723]
Hello,

We are getting critical messages like this printed in console when processing some NTFS images:
```
org.sleuthkit.datamodel.TskCoreException: Could not find parent (fsObjId: 8, parMetaAddr: 212620, parSeq: 125, parentPath: /Users/Pc/Desktop/XXXXXXX )
        at org.sleuthkit.datamodel.TskCaseDbBridge.getParentObjId(TskCaseDbBridge.java:517) ~[sleuthkit-4.11.1jar:?]
        at org.sleuthkit.datamodel.TskCaseDbBridge.addBatchedFilesToDb(TskCaseDbBridge.java:411) [sleuthkit-4.11.1.jar:?]
        at org.sleuthkit.datamodel.TskCaseDbBridge.addFile(TskCaseDbBridge.java:351) [sleuthkit-4.11.1.jar:?]
        at org.sleuthkit.datamodel.SleuthkitJNI.runAddImgNat(Native Method) ~[sleuthkit-4.11.1.jar:?]
        at org.sleuthkit.datamodel.SleuthkitJNI$CaseDbHandle$AddImageProcess.run(SleuthkitJNI.java:584) [sleuthkit-4.11.1.jar:?]
        at org.sleuthkit.datamodel.SleuthkitJNI$CaseDbHandle$AddImageProcess.run(SleuthkitJNI.java:544) [sleuthkit-4.11.1.jar:?]
        at iped.engine.datasource.SleuthkitReader.addImageBlocking(SleuthkitReader.java:611) [iped-engine-4.0.0-beta.jar:?]
        at iped.engine.datasource.SleuthkitReader$1.call(SleuthkitReader.java:664) [iped-engine-4.0.0-beta.jar:?]
        at iped.engine.datasource.SleuthkitReader$1.call(SleuthkitReader.java:661) [iped-engine-4.0.0-beta.jar:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

Mounting the image on Windows, I can see **non deleted** directory XXXXXXX and some files inside it. **Both** directory and its files are being **missed**: none of them goes to the generated sleuthkit sqlite database in tsk_files table.

Running tsk_loaddb.exe from TSK-4.11.1 on the same image, those messages aren't printed on console and the DB is populated correctly with those active files. For some reason, I think the directory entry is not being added/inserted into the DB, then TSK ignores its files because the parent is not found into the parent cache, throwing above exception. I tried to copy C fallback code to search for the parent into the DB, but is didn't work because the parent folder wasn't inserted. I also get this message printed in log:
`Attribute not found in file (tsk_fs_attrlist_get_id: Attribute 160-6 not found)`
Maybe it is related, but I'm not sure. It is not printed by tsk_loaddb.

I think there is some critical issue with the java code/jni/callback functions being called from C code while populating the DB, because pure C code (tsk_loaddb) works as expected. I spent hours today trying to find the issue, but I wasn't able.

Please, if you have any tips to debug this critical issue, I can change TSK code and run tests on the 2 NTFS triggering images we have. I would like to help fixing this as fast as possible, because I'll travel on vacation tomorrow afternoon and I would like to help fixing this before that.

This is affecting our project and probably Autopy too.

**Comment by lfcnassif** [comment]
If you are interested in fixing this into Autopsy, above commit fixed it for me. I can send a PR if you are willing to review.

**Comment by lfcnassif** [comment]
PS: this is potentially critical because a whole directory tree could be missed.

**Comment by lfcnassif** [comment]
I reinforce this is important to fix because a whole folder tree can be missed.
