### ISSUE TITLE
Hundreds of thousands of files missed because of an unexpected SID S-1-5-17 causing StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lfcnassif** [sleuthkit/sleuthkit#2765]
This was first reported at https://github.com/sepinf-inc/IPED/issues/1350

This affects IPED-4.0.4 tool and also Autopsy-4.19.3.

We have a real case VMDK image where about ~480K files from ~550K are being missed when decoding the FS using TSK-4.11.1 java API. When AddImageProcess.run(...) finishes, the following exception is thrown:
```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.sleuthkit.datamodel.WindowsAccountUtils.isWindowsSpecialSid(WindowsAccountUtils.java:155)
	at org.sleuthkit.datamodel.WindowsAccountUtils.getWindowsRealmAddress(WindowsAccountUtils.java:241)
	at org.sleuthkit.datamodel.OsAccountRealmManager.getWindowsRealm(OsAccountRealmManager.java:206)
	at org.sleuthkit.datamodel.OsAccountRealmManager.getWindowsRealm(OsAccountRealmManager.java:169)
	at org.sleuthkit.datamodel.OsAccountManager.getWindowsOsAccount(OsAccountManager.java:1013)
	at org.sleuthkit.datamodel.TskCaseDbBridge.addBatchedFilesToDb(TskCaseDbBridge.java:380)
	at org.sleuthkit.datamodel.TskCaseDbBridge.finish(TskCaseDbBridge.java:114)
	at org.sleuthkit.datamodel.SleuthkitJNI$CaseDbHandle$AddImageProcess.finishAddImageProcess(SleuthkitJNI.java:631)
	at org.sleuthkit.datamodel.SleuthkitJNI$CaseDbHandle$AddImageProcess.run(SleuthkitJNI.java:587)
	at org.sleuthkit.datamodel.SleuthkitJNI$CaseDbHandle$AddImageProcess.run(SleuthkitJNI.java:544)
```
When using tsk_loaddb cmd line tool from TSK-4.11.1, all files are added fine.

Fixing exception above, a new one is printed:
```
org.sleuthkit.datamodel.TskCoreException: Invalid SID S-1-5-17 for a host/domain
        at org.sleuthkit.datamodel.WindowsAccountUtils.getWindowsRealmAddress(WindowsAccountUtils.java:250) ~[sleuthkit-4.11.1-p3.jar:?]
        at org.sleuthkit.datamodel.OsAccountRealmManager.getWindowsRealm(OsAccountRealmManager.java:206) ~[sleuthkit-4.11.1-p3.jar:?]
        at org.sleuthkit.datamodel.OsAccountRealmManager.getWindowsRealm(OsAccountRealmManager.java:169) ~[sleuthkit-4.11.1-p3.jar:?]
        at org.sleuthkit.datamodel.OsAccountManager.getWindowsOsAccount(OsAccountManager.java:1013) ~[sleuthkit-4.11.1-p3.jar:?]
        at org.sleuthkit.datamodel.TskCaseDbBridge.addBatchedFilesToDb(TskCaseDbBridge.java:384) [sleuthkit-4.11.1-p3.jar:?]
        at org.sleuthkit.datamodel.TskCaseDbBridge.addFile(TskCaseDbBridge.java:355) [sleuthkit-4.11.1-p3.jar:?]
        at org.sleuthkit.datamodel.SleuthkitJNI.runAddImgNat(Native Method) ~[sleuthkit-4.11.1-p3.jar:?]
        at org.sleuthkit.datamodel.SleuthkitJNI$CaseDbHandle$AddImageProcess.run(SleuthkitJNI.java:585) [sleuthkit-4.11.1-p3.jar:?]
        at org.sleuthkit.datamodel.SleuthkitJNI$CaseDbHandle$AddImageProcess.run(SleuthkitJNI.java:545) [sleuthkit-4.11.1-p3.jar:?]
```
That SID S-1-5-17 is not handled properly and is breaking batch file insertion into the database.

I also think the "Error adding batched files to database" severe logging message should be logged in this case instead of propagating a RuntimeException to explicitly warn the user he/she is missing a lot of files. This was catched just because @herrmannpchw mounted the image and saw whole folders missing.

This is not VMDK specific and can happen with any NTFS image containing that SID or maybe other unexpected one.

I'm finishing a fixing PR targeting our sleuthkit fork. I can submit a PR here if you tell me you are going to review, since I submitted #2701 and #2702, very important from my point of view, but I didn't receive any kind of feedback about them, even a simple "We will review when time permits".

**Comment by lfcnassif** [comment]
This was fixed in TSK-4.12.0, so I'll close this issue. But I'll keep the PR open since I think it could be useful to avoid similar problems.
