### ISSUE TITLE
cannot read apfs DMG file

### ISSUE THREAD

**Issue by simsong** [sleuthkit/sleuthkit#3032]
`apfs-test-1.dmg` (zip attached) is an unencrypted disk image created on a Mac running Sonoma 14.6.1.
[apfs-test-1.zip](https://github.com/user-attachments/files/17295345/apfs-test-1.zip)

Here's what it looks like:
![image](https://github.com/user-attachments/assets/c87645fe-3ce4-4313-aa08-a2fb1fe54b22)

It also has a deleted file and directory, but they probably aren't recoverable.

**Comment by joachimmetz** [comment]
note that this is RAW image with a .dmg extension, but the following works (partially) for me:

```
fls -B 173 -o $(( 20480 / 512 )) /tmp/apfs-test-1.dmg 
r/r 18:	.DS_Store
r/r 23:	README.md
d/d 16:	.fseventsd
d/d 24:	dir1
free(): invalid pointer
Aborted (core dumped)
```

`free(): invalid pointer` does not look good

**Comment by joachimmetz** [comment]
```
Program received signal SIGABRT, Aborted.
Downloading source file /usr/src/debug/glibc-2.39-22.fc40.x86_64/nptl/pthread_kill.c
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44                                     
44	      return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff74a86d3 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007ffff744fc4e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7437902 in __GI_abort () at abort.c:79
#4  0x00007ffff7438767 in __libc_message_impl (fmt=fmt@entry=0x7ffff75c2330 "%s\n") at ../sysdeps/posix/libc_fatal.c:132
#5  0x00007ffff74b27e5 in malloc_printerr (str=str@entry=0x7ffff75c00a4 "free(): invalid pointer") at malloc.c:5772
#6  0x00007ffff74b4c1c in _int_free (av=<optimized out>, p=p@entry=0x4ff00f, have_lock=have_lock@entry=0) at malloc.c:4507
#7  0x00007ffff74b754e in __GI___libc_free (mem=0x4ff01f) at malloc.c:3398
#8  0x0000000000467ba1 in tsk_img_free_image_names (img_info=0x7fffe9400010) at tsk/img/img_open.cpp:631
#9  tsk_img_free (a_ptr=0x7fffe9400010) at tsk/img/img_open.cpp:693
#10 0x0000000000468921 in raw_close (img_info=0x7fffe9400010) at tsk/img/raw.c:458
#11 0x0000000000407be2 in main (argc=<optimized out>, argv1=<optimized out>) at tools/fstools/fls.cpp:436
```

**Comment by joachimmetz** [comment]
Maybe useful

```
valgrind ./tools/fstools/fls -B 173 -o $(( 20480 / 512 )) /tmp/apfs-test-1.dmg 
==3253841== Memcheck, a memory error detector
==3253841== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==3253841== Using Valgrind-3.23.0 and LibVEX; rerun with -h for copyright info
==3253841== Command: ./tools/fstools/fls -B 173 -o 40 /tmp/apfs-test-1.dmg
==3253841== 
r/r 18:	.DS_Store
r/r 23:	README.md
d/d 16:	.fseventsd
d/d 24:	dir1
==3253841== Invalid read of size 8
==3253841==    at 0x467B94: tsk_img_free_image_names (img_open.cpp:631)
==3253841==    by 0x467B94: tsk_img_free (img_open.cpp:693)
==3253841==    by 0x468920: raw_close (raw.c:458)
==3253841==    by 0x407BE1: main (fls.cpp:436)
==3253841==  Address 0x54d10f0 is 0 bytes inside a block of size 8 free'd
==3253841==    at 0x4846B83: free (vg_replace_malloc.c:989)
==3253841==    by 0x467BAE: tsk_img_free_image_names (img_open.cpp:633)
==3253841==    by 0x467BAE: tsk_img_free (img_open.cpp:693)
==3253841==    by 0x407BC7: main (fls.cpp:430)
==3253841==  Block was alloc'd at
==3253841==    at 0x484B133: calloc (vg_replace_malloc.c:1675)
==3253841==    by 0x46DEC1: tsk_malloc (mymalloc.c:32)
==3253841==    by 0x4AC149: str_vec_to_array (mult_files.cpp:103)
==3253841==    by 0x4AC149: tsk_img_findFiles (mult_files.cpp:162)
==3253841==    by 0x468A26: raw_open (raw.c:644)
==3253841==    by 0x467626: tsk_img_open (img_open.cpp:277)
==3253841==    by 0x407B2F: main (fls.cpp:297)
==3253841== 
==3253841== Invalid free() / delete / delete[] / realloc()
==3253841==    at 0x4846B83: free (vg_replace_malloc.c:989)
==3253841==    by 0x467BA0: tsk_img_free_image_names (img_open.cpp:631)
==3253841==    by 0x467BA0: tsk_img_free (img_open.cpp:693)
==3253841==    by 0x468920: raw_close (raw.c:458)
==3253841==    by 0x407BE1: main (fls.cpp:436)
==3253841==  Address 0x54d1140 is 0 bytes inside a block of size 21 free'd
==3253841==    at 0x4846B83: free (vg_replace_malloc.c:989)
==3253841==    by 0x467BA0: tsk_img_free_image_names (img_open.cpp:631)
==3253841==    by 0x467BA0: tsk_img_free (img_open.cpp:693)
==3253841==    by 0x407BC7: main (fls.cpp:430)
==3253841==  Block was alloc'd at
==3253841==    at 0x484B133: calloc (vg_replace_malloc.c:1675)
==3253841==    by 0x46DEC1: tsk_malloc (mymalloc.c:32)
==3253841==    by 0x4AC1A2: str_vec_to_array (mult_files.cpp:110)
==3253841==    by 0x4AC1A2: tsk_img_findFiles (mult_files.cpp:162)
==3253841==    by 0x468A26: raw_open (raw.c:644)
==3253841==    by 0x467626: tsk_img_open (img_open.cpp:277)
==3253841==    by 0x407B2F: main (fls.cpp:297)
==3253841== 
==3253841== Invalid free() / delete / delete[] / realloc()
==3253841==    at 0x4846B83: free (vg_replace_malloc.c:989)
==3253841==    by 0x467BAE: tsk_img_free_image_names (img_open.cpp:633)
==3253841==    by 0x467BAE: tsk_img_free (img_open.cpp:693)
==3253841==    by 0x468920: raw_close (raw.c:458)
==3253841==    by 0x407BE1: main (fls.cpp:436)
==3253841==  Address 0x54d10f0 is 0 bytes inside a block of size 8 free'd
==3253841==    at 0x4846B83: free (vg_replace_malloc.c:989)
==3253841==    by 0x467BAE: tsk_img_free_image_names (img_open.cpp:633)
==3253841==    by 0x467BAE: tsk_img_free (img_open.cpp:693)
==3253841==    by 0x407BC7: main (fls.cpp:430)
==3253841==  Block was alloc'd at
==3253841==    at 0x484B133: calloc (vg_replace_malloc.c:1675)
==3253841==    by 0x46DEC1: tsk_malloc (mymalloc.c:32)
==3253841==    by 0x4AC149: str_vec_to_array (mult_files.cpp:103)
==3253841==    by 0x4AC149: tsk_img_findFiles (mult_files.cpp:162)
==3253841==    by 0x468A26: raw_open (raw.c:644)
==3253841==    by 0x467626: tsk_img_open (img_open.cpp:277)
==3253841==    by 0x407B2F: main (fls.cpp:297)
==3253841== 
==3253841== 
==3253841== HEAP SUMMARY:
==3253841==     in use at exit: 3,080 bytes in 1 blocks
==3253841==   total heap usage: 822 allocs, 823 frees, 4,390,282 bytes allocated
==3253841== 
==3253841== LEAK SUMMARY:
==3253841==    definitely lost: 0 bytes in 0 blocks
==3253841==    indirectly lost: 0 bytes in 0 blocks
==3253841==      possibly lost: 0 bytes in 0 blocks
==3253841==    still reachable: 3,080 bytes in 1 blocks
==3253841==         suppressed: 0 bytes in 0 blocks
==3253841== Rerun with --leak-check=full to see details of leaked memory
==3253841== 
==3253841== For lists of detected and suppressed errors, rerun with: -s
==3253841== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
```
