### ISSUE TITLE
TSK-4.4 Java Bindings not working on Linux

### ISSUE THREAD

**Issue by lfcnassif** [sleuthkit/sleuthkit#799]
Everything compiles and installs ok. But when using java bindings from our java app, the following error is thrown:

> Caused by: java.lang.UnsatisfiedLinkError:  /mnt/Volume0/tmp/indexador-temp1490888200880/libtsk_jni.so:  /mnt/Volume0/tmp/indexador-temp1490888200880/libtsk_jni.so: undefined  symbol: _ZTV19TskIsImageSupported 
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)  ~[?:1.8.0_121] 
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)  ~[?:1.8.0_121] 
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)  ~[?:1.8.0_121] 
    at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_121] 
    at java.lang.System.load(System.java:1086) ~[?:1.8.0_121] 
    at  org.sleuthkit.datamodel.LibraryUtils.loadNativeLibFromTskJar(LibraryUtils.java:207)  ~[tsk-datamodel-4.4-p1.jar:?] 
    at  org.sleuthkit.datamodel.LibraryUtils.loadSleuthkitJNI(LibraryUtils.java:73)  ~[tsk-datamodel-4.4-p1.jar:?] 
    at  org.sleuthkit.datamodel.SleuthkitJNI.<clinit>(SleuthkitJNI.java:49)  ~[tsk-datamodel-4.4-p1.jar:?] 
    at  org.sleuthkit.datamodel.SleuthkitCase.newCase(SleuthkitCase.java:1173)  ~[tsk-datamodel-4.4-p1.jar:?] 
    at  dpf.sp.gpinf.indexer.datasource.SleuthkitReader.read(SleuthkitReader.java:263)  ~[iped.jar:?] 
    at  dpf.sp.gpinf.indexer.datasource.ItemProducer.run(ItemProducer.java:104)  ~[iped.jar:?] 

Seems like TskIsImageSupported class was not found. Commenting the function Java_org_sleuthkit_datamodel_SleuthkitJNI_isImageSupportedNat() in dataModel_SleuthkitJNI.cpp is a workaround for the problem (seems like that function is not used anywhere).

This issue does not happen on Windows nor with TSK-4.3 on Linux

**Comment by lfcnassif** [comment]
This still happens with TSK-4.4.2. There is a better fix for the issue?

**Comment by bcarrier** [comment]
Can you try the release-4.5.0 branch?  It looks like that class was not being compiled into libtsk for autoconf/make builds.

**Comment by lfcnassif** [comment]
Thanks, Brian. That worked!
