### ISSUE TITLE
fls hangs on corrupt exfat image.

### ISSUE THREAD

**Issue by adambuchbinder** [sleuthkit/sleuthkit#906]
To reproduce:

    $ unzip hang.zip
    Archive:  hang.zip
      inflating: hang.img
    $ fls hang.img
    [hangs here]

This bug was found using [american fuzzy lop](http://lcamtuf.coredump.cx/afl/) and input files ultimately from [files.fuzzing-project.org](https://files.fuzzing-project.org/filesystems/).

Backtrace:

```
^C
Program received signal SIGINT, Interrupt.
tsk_img_read (a_img_info=0x7ffff7f8f010, a_off=77824, 
    a_buf=a_buf@entry=0x7c11b0 "\364\037\365\037\366\037\367\037\370\037\371\037\372\037\373\037\363\037\375\037\376\037\377\037", a_len=512) at img_io.c:34
34	    if (a_img_info == NULL) {
(gdb) bt
#0  tsk_img_read (a_img_info=0x7ffff7f8f010, a_off=77824, 
    a_buf=a_buf@entry=0x7c11b0 "\364\037\365\037\366\037\367\037\370\037\371\037\372\037\373\037\363\037\375\037\376\037\377\037", a_len=512) at img_io.c:34
#1  0x0000000000578a3e in tsk_fs_read_block (a_fs=a_fs@entry=0x7bccd0, 
    a_addr=a_addr@entry=152, 
    a_buf=a_buf@entry=0x7c11b0 "\364\037\365\037\366\037\367\037\370\037\371\037\372\037\373\037\363\037\375\037\376\037\377\037", a_len=<optimized out>)
    at fs_io.c:164
#2  0x00000000005831d6 in exfatfs_get_alloc_bitmap (a_fatfs=0x7bccd0)
    at exfatfs.c:261
#3  exfatfs_open (a_fatfs=0x7bccd0) at exfatfs.c:530
#4  0x000000000052fd31 in fatfs_open (a_img_info=<optimized out>, 
    a_offset=<optimized out>, a_ftype=TSK_FS_TYPE_FAT_DETECT, 
    a_test=<optimized out>) at fatfs.c:123
#5  0x0000000000431098 in tsk_fs_open_img (a_img_info=0x7ffff7f8f010, 
    a_offset=0, a_ftype=<optimized out>) at fs_open.c:124
#6  0x00000000004098f4 in main (argc=<optimized out>, argv1=<optimized out>)
    at fls.cpp:267
```

Input: [hang.zip](https://github.com/sleuthkit/sleuthkit/files/1250271/hang.zip)

**Comment by adambuchbinder** [comment]
The issue here appears to be that current_sector is never incremented if the root sector doesn't contain the expected allocation bitmap.

https://github.com/sleuthkit/sleuthkit/blob/ed9c2c8fdfed87079595513286e238a1a71bcd5b/tsk/fs/exfatfs.c#L257
