### ISSUE TITLE
fls deadlocks due to recursive call to tsk_fs_dir_find_orphans().

### ISSUE THREAD

**Issue by adambuchbinder** [sleuthkit/sleuthkit#928]
To reproduce:

    $ unzip deadlock.zip
    Archive:  deadlock.zip
      inflating: deadlock.img
    $ fls -f iso9660 deadlock.img
    [hangs here]

This bug was found using [american fuzzy lop](http://lcamtuf.coredump.cx/afl/) and input files ultimately from [files.fuzzing-project.org](https://files.fuzzing-project.org/filesystems/).

Backtrace:

```
#0  __lll_lock_wait ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff7493649 in _L_lock_909 ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007ffff7493470 in __GI___pthread_mutex_lock (mutex=0x7cedb8)
    at ../nptl/pthread_mutex_lock.c:79
#3  0x000000000050b091 in tsk_take_lock (lock=lock@entry=0x7cedb8)
    at tsk_lock.c:88
#4  0x000000000042509b in tsk_fs_dir_find_orphans (a_fs=0x7cecd0, 
    a_fs_dir=0x7d2b40) at fs_dir.c:1159
#5  0x000000000041f020 in tsk_fs_dir_open_meta (a_fs=<optimized out>, 
    a_addr=<optimized out>) at fs_dir.c:290
#6  0x000000000041f511 in tsk_fs_dir_walk_lcl (a_fs=a_fs@entry=0x7cecd0, 
    a_dinfo=a_dinfo@entry=0x7fffffffaf50, a_addr=a_addr@entry=0, 
    a_flags=a_flags@entry=(TSK_FS_DIR_WALK_FLAG_UNALLOC | TSK_FS_DIR_WALK_FLAG_RECURSE | TSK_FS_DIR_WALK_FLAG_NOORPHAN), 
    a_action=a_action@entry=0x41ad40 <load_named_dir_walk_cb>, 
    a_ptr=a_ptr@entry=0x0) at fs_dir.c:556
#7  0x0000000000421f39 in tsk_fs_dir_walk (a_fs=a_fs@entry=0x7cecd0, a_addr=0, 
    a_flags=a_flags@entry=(TSK_FS_DIR_WALK_FLAG_UNALLOC | TSK_FS_DIR_WALK_FLAG_RECURSE | TSK_FS_DIR_WALK_FLAG_NOORPHAN), 
    a_action=a_action@entry=0x41ad40 <load_named_dir_walk_cb>, 
    a_ptr=a_ptr@entry=0x0) at fs_dir.c:817
#8  0x0000000000424fa5 in tsk_fs_dir_walk (a_ptr=0x0, 
    a_action=0x41ad40 <load_named_dir_walk_cb>, 
    a_flags=(TSK_FS_DIR_WALK_FLAG_UNALLOC | TSK_FS_DIR_WALK_FLAG_RECURSE | TSK_FS_DIR_WALK_FLAG_NOORPHAN), a_addr=<optimized out>, a_fs=0x7cecd0)
    at /usr/include/x86_64-linux-gnu/bits/stdio2.h:97
#9  tsk_fs_dir_load_inum_named (a_fs=a_fs@entry=0x7cecd0) at fs_dir.c:966
#10 0x0000000000425a3b in tsk_fs_dir_find_orphans (a_fs=0x7cecd0, 
    a_fs_dir=0x7d00d0) at fs_dir.c:1185
#11 0x000000000041f020 in tsk_fs_dir_open_meta (a_fs=<optimized out>, 
    a_addr=<optimized out>) at fs_dir.c:290
#12 0x000000000041f511 in tsk_fs_dir_walk_lcl (a_fs=a_fs@entry=0x7cecd0, 
    a_dinfo=a_dinfo@entry=0x7fffffffc550, a_addr=a_addr@entry=0, 
    a_flags=a_flags@entry=(TSK_FS_DIR_WALK_FLAG_ALLOC | TSK_FS_DIR_WALK_FLAG_UNALLOC), a_action=a_action@entry=0x418a10 <print_dent_act>, 
    a_ptr=a_ptr@entry=0x7fffffffd9c0) at fs_dir.c:556
#13 0x0000000000421f39 in tsk_fs_dir_walk (a_fs=0x7cecd0, a_addr=0, 
    a_flags=<optimized out>, a_action=0x418a10 <print_dent_act>, 
    a_ptr=0x7fffffffd9c0) at fs_dir.c:817
#14 0x00000000004244e9 in tsk_fs_dir_walk (a_fs=<optimized out>, 
    a_addr=<optimized out>, a_flags=<optimized out>, 
    a_action=a_action@entry=0x418a10 <print_dent_act>, 
    a_ptr=a_ptr@entry=0x7fffffffd9c0) at fs_dir.c:841
#15 0x000000000041a8ae in tsk_fs_fls (fs=<optimized out>, 
    lclflags=<optimized out>, inode=<optimized out>, flags=<optimized out>, 
    tpre=<optimized out>, skew=<optimized out>) at fls_lib.c:262
#16 0x000000000040999f in main (argc=<optimized out>, argv1=<optimized out>)
    at fls.cpp:308
```

It looks like `tsk_fs_dir_find_orphans()` takes a lock on the filesystem whenever it's called, so a recursive call (note that it appears twice in the backtrace) will deadlock.

Input: [deadlock.zip](https://github.com/sleuthkit/sleuthkit/files/1257837/deadlock.zip)

**Comment by jtsylve** [comment]
Note: my PR commit message had the wrong issue #
